openapi: 3.0.0
info:
  title: Local Frontend-Backend Integration for RAG Chatbot
  description: API for chatbot functionality with RAG integration
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

paths:
  /chat:
    post:
      summary: Process user query and return RAG-generated response
      description: Sends a user query to the RAG system and returns a response based on book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the RAG system
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check for the RAG service
      description: Checks the health status of the RAG service and its dependencies
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's question or input text
          example: "What is ROS 2?"
        selected_text:
          type: string
          description: Text selected on the page by the user (optional context)
          example: "ROS 2 is a flexible framework for writing robot software."
        session_id:
          type: string
          description: Session identifier (generated if not provided)
          example: "550e8400-e29b-41d4-a716-446655440000"

    ChatResponse:
      type: object
      required:
        - response
        - session_id
        - sources
        - timestamp
      properties:
        response:
          type: string
          description: The generated response from the RAG system
          example: "ROS 2 (Robot Operating System 2) is a flexible framework for writing robot software..."
        session_id:
          type: string
          description: Session identifier for the conversation
          example: "550e8400-e29b-41d4-a716-446655440000"
        sources:
          type: array
          items:
            $ref: '#/components/schemas/SourceReference'
          description: Sources referenced in the response
        timestamp:
          type: string
          format: date-time
          description: When the response was generated

    SourceReference:
      type: object
      properties:
        url:
          type: string
          description: URL of the source document
          example: "https://physical-ai-humanoid-robotics-book/robotics-intro"
        title:
          type: string
          description: Title of the source document
          example: "Introduction to Robotics"
        snippet:
          type: string
          description: Excerpt from the source document
          example: "Robotics is an interdisciplinary branch of engineering..."

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "Invalid input parameters"

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          description: Overall health status
          example: "healthy"
          enum: [healthy, unhealthy]
        timestamp:
          type: string
          format: date-time
          description: When the health check was performed
        dependencies:
          type: object
          additionalProperties:
            type: string
            description: Status of each dependency
            example:
              qdrant: "ok"
              gemini: "ok"
              database: "ok"